### ISSUE TITLE
Bug in error handling

### ISSUE THREAD

**Issue by johntmyers** [workos-inc/workos-python#94]
Currently calling `str()` on any of the inherited exception classes will fail due to not setting the `error_description` attr to `None` by default.

https://github.com/workos-inc/workos-python/blob/722a468a7deb2999c341a01f430afe8ac6dd26f8/workos/exceptions.py#L7

**Comment by blairlunceford** [comment]
​I pushed a fix in the latest patch release of the Python SDK, 1.4.1, can you test with this new version?
​
​https://github.com/workos-inc/workos-python/releases/tag/v1.4.1
​
​Thanks!
